now processing task id:: 5161 on worker3.slurm.hj.se
2025-05-16 11:37:50.565635: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1747395473.469420 1836382 gpu_device.cc:2018] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 8098 MB memory:  -> device: 0, name: NVIDIA A100 80GB PCIe MIG 1g.10gb, pci bus id: 0000:81:00.0, compute capability: 8.0
2025-05-16 11:38:13.384917: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:453] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 1032 of 11303
2025-05-16 11:38:33.274147: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:453] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 4142 of 11303
2025-05-16 11:38:43.386120: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:453] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 5539 of 11303
2025-05-16 11:38:53.472416: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:453] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 7126 of 11303
2025-05-16 11:39:03.488789: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:453] ShuffleDatasetV3:2: Filling up shuffle buffer (this may take a while): 8528 of 11303
2025-05-16 11:39:20.646765: I tensorflow/core/kernels/data/shuffle_dataset_op.cc:483] Shuffle buffer filled.
2025-05-16 11:39:21.052688: I external/local_xla/xla/service/service.cc:152] XLA service 0x7f29480035c0 initialized for platform CUDA (this does not guarantee that XLA will be used). Devices:
2025-05-16 11:39:21.052772: I external/local_xla/xla/service/service.cc:160]   StreamExecutor device (0): NVIDIA A100 80GB PCIe MIG 1g.10gb, Compute Capability 8.0
2025-05-16 11:39:21.377501: I tensorflow/compiler/mlir/tensorflow/utils/dump_mlir_util.cc:269] disabling MLIR crash reproducer, set env var `MLIR_CRASH_REPRODUCER_DIRECTORY` to enable.
I0000 00:00:1747395563.097108 1837028 cuda_dnn.cc:529] Loaded cuDNN version 90300
2025-05-16 11:39:34.571750: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8694', 88 bytes spill stores, 88 bytes spill loads

2025-05-16 11:39:35.418128: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8694', 16 bytes spill stores, 16 bytes spill loads

I0000 00:00:1747395589.514094 1837028 device_compiler.h:196] Compiled cluster using XLA!  This line is logged at most once for the lifetime of the process.
2025-05-16 11:41:11.088122: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8694', 88 bytes spill stores, 88 bytes spill loads

2025-05-16 11:41:12.184619: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_8694', 16 bytes spill stores, 16 bytes spill loads

2025-05-16 11:41:33.981390: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_2460', 188 bytes spill stores, 188 bytes spill loads

2025-05-16 11:41:34.044057: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_2467', 188 bytes spill stores, 188 bytes spill loads

2025-05-16 11:41:34.121309: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_2460', 220 bytes spill stores, 220 bytes spill loads

2025-05-16 11:41:34.129856: I external/local_xla/xla/stream_executor/cuda/subprocess_compilation.cc:346] ptxas warning : Registers are spilled to local memory in function 'gemm_fusion_dot_2467', 220 bytes spill stores, 220 bytes spill loads

2025-05-16 11:42:13.424379: W tensorflow/core/framework/op_kernel.cc:1856] OP_REQUIRES failed at xla_ops.cc:590 : INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_one_step_on_data_100694[] on XLA_GPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_GPU_JIT devices compatible with node {{node data_2}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, _output_shapes=[[8]], _user_specified_name="data", index=2){{node data_2}}
The op is created at: 
File "fashion_plates_dating/fashion.py", line 761, in <module>
File "fashion_plates_dating/fashion.py", line 739, in main
File "fashion_plates_dating/fashion.py", line 373, in train_and_evaluate
File "fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 560, in predict
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 259, in one_step_on_data_distributed
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>
	tf2xla conversion failed while converting __inference_one_step_on_data_100694[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
2025-05-16 11:42:13.424501: I tensorflow/core/framework/local_rendezvous.cc:407] Local rendezvous is aborting with status: INVALID_ARGUMENT: Detected unsupported operations when trying to compile graph __inference_one_step_on_data_100694[] on XLA_GPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_GPU_JIT devices compatible with node {{node data_2}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, _output_shapes=[[8]], _user_specified_name="data", index=2){{node data_2}}
The op is created at: 
File "fashion_plates_dating/fashion.py", line 761, in <module>
File "fashion_plates_dating/fashion.py", line 739, in main
File "fashion_plates_dating/fashion.py", line 373, in train_and_evaluate
File "fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 560, in predict
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 259, in one_step_on_data_distributed
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>
	tf2xla conversion failed while converting __inference_one_step_on_data_100694[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[StatefulPartitionedCall]]
Traceback (most recent call last):
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 761, in <module>
    main()
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 739, in main
    metrics = train_and_evaluate(
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 373, in train_and_evaluate
    y_true_years_rounded, preds_years_rounded, image_paths = collect_regression_predictions(
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions
    preds = model.predict(val_ds_unshuffled_batched, verbose=0)
  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 122, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/python/eager/execute.py", line 53, in quick_execute
    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
tensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:

Detected at node data_2 defined at (most recent call last):
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 761, in <module>

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 739, in main

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 373, in train_and_evaluate

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 560, in predict

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 346, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>

Detected at node data_2 defined at (most recent call last):
  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 761, in <module>

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 739, in main

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 373, in train_and_evaluate

  File "/home/anjo19go/fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 560, in predict

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 346, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value

  File "/home/anjo19go/micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>

Detected unsupported operations when trying to compile graph __inference_one_step_on_data_100694[] on XLA_GPU_JIT: _Arg (No registered '_Arg' OpKernel for XLA_GPU_JIT devices compatible with node {{node data_2}}
	 (OpKernel was found, but attributes didn't match) Requested Attributes: T=DT_STRING, _output_shapes=[[8]], _user_specified_name="data", index=2){{node data_2}}
The op is created at: 
File "fashion_plates_dating/fashion.py", line 761, in <module>
File "fashion_plates_dating/fashion.py", line 739, in main
File "fashion_plates_dating/fashion.py", line 373, in train_and_evaluate
File "fashion_plates_dating/fashion.py", line 219, in collect_regression_predictions
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py", line 117, in error_handler
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 560, in predict
File "micromamba/envs/tf_new/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py", line 259, in one_step_on_data_distributed
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/polymorphism/function_type.py", line 356, in placeholder_arguments
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 250, in placeholder_value
File "micromamba/envs/tf_new/lib/python3.10/site-packages/tensorflow/core/function/trace_type/default_types.py", line 251, in <listcomp>
	tf2xla conversion failed while converting __inference_one_step_on_data_100694[]. Run with TF_DUMP_GRAPH_PREFIX=/path/to/dump/dir and --vmodule=xla_compiler=2 to obtain a dump of the compiled functions.
	 [[StatefulPartitionedCall]] [Op:__inference_one_step_on_data_distributed_101485]
finished task with id:: 5161
